### ISSUE TITLE
채팅 이전

### ISSUE THREAD

**Issue by lifthrasiir** [rust-kr/rust-kr-rust#32]
채팅이 계속 죽어 있는데 그냥 지우고 webchat.ozinger.org로 링크하게 합시다.

**Comment by simnalamburt** [comment]
Closed by https://github.com/rust-kr/rust-kr.org/wiki/Home/_compare/c0c914df18903ae97a1ba3120c85e41c962def93...6786ce1951a15f25768eeb2fbb43a1601bddeca5
