### ISSUE TITLE
`docs/`를 별도 repo로 분리하기

### ISSUE THREAD

**Issue by klutzy** [rust-kr/rust-kr-rust#7]

**Comment by sanxiyn** [comment]
이거 별도로 분리해야 될까요? 안 해도 될 것 같은데요.

**Comment by klutzy** [comment]
전에는 모임 문서 같은 걸 local에서 수정하는 게 번거로워서, github wiki같은 데에 편집한 다음 서버는 주기적인 fetch를 하도록 하면 어떨까 싶었던 것 같네요.
지금 생각하면 이쪽이 더 번잡한 듯 하니 닫습니다.
