### ISSUE TITLE
rustdoc 파싱 오류 해결

### ISSUE THREAD

**Issue by klutzy** [rust-kr/rust-kr-rust#8]
현재는 markdown 렌더링에 `rustdoc::html::markdown`을 이용하고 있습니다. 하지만 이 녀석은 이상한 md 문서를 만나면 panic하는 문제가 있습니다.

예를 들어, [이전에 발견된 문제](https://github.com/rust-kr/rust-kr-rust/pull/6#issuecomment-73889931)는 code highlight을 libsyntax 파서에 의존하는데 코드가 아닌 녀석이 코드로 취급되면서 파싱 에러가 났던 경우입니다.

현재 떠오르는 해결 방법은 두 가지입니다. 1) 해당 markdown 부분을 떼와서 highlight 없애고 + panic할 수 있는 부분 더 없애기 2) 파싱 루틴을 별도 스레드로 빼서 panic catch하기

**Comment by simnalamburt** [comment]
이거 이제 닫아도 되지 않나요?

**Comment by klutzy** [comment]
현재는 [pulldown-cmark](https://github.com/google/pulldown-cmark)를 씁니다. 코드를 잠깐 봤는데 panic과 unwrap이 있긴 합니다. (파서 내부 동작 assertion같이 생기긴 했네요.) 문제가 되면 그때 다시 살펴보도록 합시다.
